system("pwd")
system("paup -n get.tree.snp.chr1.1.nex >/dev/null")
system("grep 'PAUP_1' chr1.1.tre | sed 's/^.*: //' > snp.1.tre ")
temp.tree<-read.table(file="snp.1.tre")
tree<-unlist(temp.tree[5])
tree<-as.character(tree)
write(tree,file="tree.txt")
tree<-read.newick(file="tree.txt")
plot(tree)
#phy<-read.newick(text = tree)
phy1<-chronoMPL(tree)
plot(phy1)
#################################################################
system("paup -n get.tree.snp.chr1.0.nex >/dev/null")
system("grep 'PAUP_1' chr1.0.tre | sed 's/^.*: //' > snp.1.tre ")
temp.tree<-read.table(file="snp.1.tre")
tree<-unlist(temp.tree[5])
tree<-as.character(tree)
write(tree,file="tree.txt")
tree<-read.newick(file="tree.txt")
plot(tree)
phy2<-chronoMPL(tree)
plot(phy2)
################################################################
system("paup -n get.tree.snp.chr5.0.nex >/dev/null")
system("grep 'PAUP_1' chr5.0.tre | sed 's/^.*: //' > snp.1.tre ")
temp.tree<-read.table(file="snp.1.tre")
tree<-unlist(temp.tree[5])
tree<-as.character(tree)
write(tree,file="tree.txt")
tree5.0<-read.newick(file="tree.txt")
plot(tree5.0)
phy3<-chronoMPL(tree5.0)
plot(phy3)
################################################################
system("paup -n get.tree.snp.chr5.1.nex >/dev/null")
system("grep 'PAUP_1' chr5.1.tre | sed 's/^.*: //' > snp.1.tre ")
temp.tree<-read.table(file="snp.1.tre")
tree<-unlist(temp.tree[5])
tree<-as.character(tree)
write(tree,file="tree.txt")
tree5.1<-read.newick(file="tree.txt")
plot(tree5.1)
phy4<-chronoMPL(tree5.1)
plot(phy4)
################################################################
system("paup -n get.tree.snp.chr8.0.nex >/dev/null")
system("grep 'PAUP_1' chr8.0.tre | sed 's/^.*: //' > snp.1.tre ")
temp.tree<-read.table(file="snp.1.tre")
tree<-unlist(temp.tree[5])
tree<-as.character(tree)
write(tree,file="tree.txt")
tree8.0<-read.newick(file="tree.txt")
plot(tree8.0)
phy5<-chronoMPL(tree8.0)
plot(phy5)
##################################################################
system("paup -n get.tree.snp.chr8.1.nex >/dev/null")
system("grep 'PAUP_1' chr8.1.tre | sed 's/^.*: //' > snp.1.tre ")
temp.tree<-read.table(file="snp.1.tre")
tree<-unlist(temp.tree[5])
tree<-as.character(tree)
write(tree,file="tree.txt")
tree8.1<-read.newick(file="tree.txt")
plot(tree8.1)
phy6<-chronoMPL(tree8.1)
plot(phy6)

#################################################################
# rm(list=ls())
library(ape)
library(phytools)
tree1<-rtree(5)
plot(tree1)
tree2<-rtree(5)
plot(tree2)
y<-list(tree1=tree1,tree2=tree2)
class(y) <- "multiPhylo"
contree<-averageTree(y, start=NULL, method="quadratic.path.difference",tol=1e-12, quiet=FALSE)
plot(contree)
contree2<-consensus(y,p=0.8)
plot(contree2)
contree3<-ls.consensus(y,tol=1e-3)
plot(contree3)
#################################################################
setwd("~/Dropbox/FCU/Teaching/Mentoring/2017Spring/YiWeiHsu/Rcode/main.code/micezhangdataset/")
load("realtree.RData")
y1<-list(phy1=phy1, phy2=phy2)
class(y1) <- "multiPhylo"
#contree1<-averageTree(y1, start = NULL,method="quadratic.path.difference",tol=1e-12, quiet=FALSE)
#plot(contree1)
contree<-ls.consensus(y1,tol=1e-3)
plot(contree)
#################################################################
y5<-list(phy3=phy3, phy4=phy4)
class(y5) <- "multiphylo"
#contree5<-averageTree(y5, start = NULL,method="quadratic.path.difference",tol=1e-12, quiet=FALSE)
#plot(contree5)
contree5<-ls.consensus(y5,tol=1e-3)
plot(contree5)
#################################################################
y8<-list(phy5=phy5, phy6=phy6)
class(y8) <- "multiphylo"
#contree8<-averageTree(y8, start = NULL,method="quadratic.path.difference",tol=1e-12, quiet=FALSE)
#plot(contree8)
contree8<-ls.consensus(y8,tol=1e-3)
plot(contree8)
#################################################################
#save.image("realtree.RData")
#################################################################
load("contree1.RData")
load("contree5.RData")
load("contree8.RData")
plot(contree1)
plot(contree5)
plot(contree8)

